[package]
name = "electionguard"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.7", features = ["derive"] }

eg = { path = "../eg" }
util = { path = "../util" }
